config/routes.rb
Rails.application.routes.draw do
  devise_for :teams
  resources :homeworks

  resources :teams
  root 'homeworks#index'

end

app/models/homework.rb
class Homework < ActiveRecord::Base
    belongs_to :team
    
    validates :title , presence: true
    validates :description , presence: true
    validates :duration , presence: true
    validates :startdate , presence: true
    validates :enddate , presence: true
    validates :team_id , presence: true
    
    validates :duration, numericality: { only_float: true }
    
    

end

app/models/team.rb
class Team < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :homeworks
    validates :name , presence: true
    validates :lastname , presence: true
    validates :email , presence: true
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  before_action :configure_permitted_parameters, if: :devise_controller?
 
protected
 
def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) do |u|
    u.permit(:name, :lastname, :email, :password, :password_confirmation)
  end
  devise_parameter_sanitizer.for(:account_update) do |u|
    u.permit(:name, :lastname, :email, :password, :password_confirmation, :current_password, :biography, :location, :profile)
  end
end
  
  

end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]
before_action :get_teams, only: [:new, :create, :edit, :update]
  before_action :authenticate_team!, only: [:new, :create, :edit, :update, :destroy]
  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.order('finished ASC').order('enddate ASC')
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)
    
    @homework = Homework.new(homework_params)
    @homework.team_id = current_team.id

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    
    def get_teams
      @member = Team.all.map {|team| [team.name, team.id]}
    end
    
    def homework_params
      params.require(:homework).permit(:title, :description, :duration, :startdate, :enddate, :team_id, :finished)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
      def flass_class(type)
    case type
      when :success then "success"
      when :error   then "warning"
      when :alert   then "warning"
      when :notice  then ""
      else "info"
    end
  end
    

end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/homeworks/_form.html.erb
<%= form_for(@homework, multipart: true) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br>
    <%= f.datetime_select :enddate %>
  </div>

  <div class="field">
    <%= f.label :finished %><br>
    <%= f.check_box :finished %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<h1><%= t('Listing homeworks') %></h1>


<table>
  <thead>
    <tr>
      <th><%= t('Title') %></th>
      <th><%= t('Duration') %></th>
      <th><%= t('Startdate') %></th>
      <th><%= t('Enddate') %></th>
      <th><%= t('Member') %></th>
      <th><%= t('Finished') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.title %></td>
        <td><%= homework.duration %></td>
        <td><%= homework.startdate %></td>
        <td><%= homework.enddate %></td>
        <td><%= homework.team.name %></td>
        <td><%= homework.finished %></td>
        <td><%= link_to t('Show'), homework %></td>
        <td><%= link_to t('Edit'), edit_homework_path(homework) %></td>
        <td><%= link_to t('Destroy'), homework, method: :delete, data: { confirm: t('Are you sure?') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('New Homework'), new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @homework.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @homework.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @homework.duration %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @homework.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @homework.enddate %>
</p>

<p>
  <strong>Team:</strong>
  <%= @homework.team.name %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @homework.finished %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Trello" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    
    <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1>
            <%= link_to 'Trello', root_path %>

      </h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  
  
  
  
  <section class="top-bar-section">
    
        <!-- Left Nav Section -->
    <ul class="left">
      <li>
      <%= link_to t('Teams'), teams_path %></li>
      <li><%= link_to t('Homeworks'), homeworks_path %>
      </li>
    </ul>
    
    
        <!-- Right Nav Section -->
        <ul class="right">
          <% if team_signed_in? %>
          <li class="active">
            <%= link_to current_team.name, edit_team_registration_path %>
          </li>
          <li>
            <%= link_to t('Sign Out'), destroy_team_session_path, method: :delete %>
          </li>
          
          
          
        
  </section>
          
          
          
          <% else %>
          <li class="active">
            <%= link_to t('Sign Up'), new_team_registration_path %>
          </li>
          <li>
            <%= link_to t('Sign In'), new_team_session_path %>
          </li>
          <% end %>
        </ul>
    
        <!-- Left Nav Section -->

      </section>
  

</nav>

    
    
    
    
    <div class="row">
    <div class="columns large-12">
    <% flash.each do |type, message| %>
    <div data-alert class="alert-box radius <%= flass_class type %>">
    <%= message %>
    <a href="#" class="close">&times;</a>
    </div>
    <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>